### ISSUE TITLE
Figure out a way to update MPLAB's project directory structure without overwriting build configs.

### ISSUE THREAD

**Issue by Kiboneu** [ProgHQ/open-tl866#15]
Normally, it appears that `configurations.xml` stores both the directory structure of the project (to aid the linker) and build, environment, programmer configurations. The problem is that different contributors might use different programmers and various options for personal use while the project structure has to be kept updated when new files are introduced. So latest commits will end up overwriting other contributors' preferences...

One solution might be to use different profiles in the project configuration, which the latest MPLAB IDE has. Once I have access to my windows machine (June 4th or 5th), I can check that out.

**Comment by Elemecca** [comment]
I'm pretty sure this is obsoleted by the switch to CMake (#32).

**Comment by JohnDMcMaster** [comment]
Obsolete
