### ISSUE TITLE
Attempt to run open-tl866 python scripts on RasPi

### ISSUE THREAD

**Issue by RobertBaruch** [ProgHQ/open-tl866#69]
Since open-tl866 is difficult if not impossible to get running under Windows or a Linux VM, see if it's possible to run at least the python scripts with a Raspberry Pi. It may not be possible to run the xc8 compiler under RasPi since that requires ARM binaries.

**Comment by JohnDMcMaster** [comment]
What is the issue getting it to run under a Linux VM?

**Comment by JohnDMcMaster** [comment]
Okay I now see the IRC cmments about your virtual box issues. Unfortunately I won't have access to a Windows machine for a month or so. Have you tried VMWare?

**Comment by RobertBaruch** [comment]
I was going to try it, but first I wanted to hack on an RPi.

**Comment by RobertBaruch** [comment]
There's no fundamental reason why the python scripts wouldn't work under RPi. However, the full suite would need to migrate to sdcc if you wanted to develop on an RPi.
