### ISSUE TITLE
Oversight in readme: "using an ICSP programmer"

### ISSUE THREAD

**Issue by flarn2006** [ProgHQ/open-tl866#82]
> If you flashed the open firmware using an ICSP programmer the bootloader has been erased from your TL866.

Shouldn't this say "using *another* ICSP programmer"? Technically, you're flashing it using an ICSP programmer even if you do so via the bootloader—I mean, what do you think the bootloader is running on? ;)

**Comment by cr1901** [comment]
Indeed, we don't support using your tl866 in ouroboros configuration :). Fixed.

**Comment by JohnDMcMaster** [comment]
Thanks @flarn2006 for reaching out! If I may ask, what is your interest in the project? FYI developers can also be directly reached on freenode IRC channel #proghq. Would love to hear more about your project!
